### PR TITLE
Rename linux wheels to manylinux_2_27

### PR DESCRIPTION
**Pull request by TheTripleV**
This should be all that's needed for manylinux?

### CODE REVIEW

**Comment by virtuald** [comment]
This would rename the roborio/raspbian wheels too.

**Comment by TheTripleV** [comment]
No?
It only renames linux_x86_64 files so those should be excluded.

**Comment by virtuald** [comment]
Oh, I didn't notice that. Won't the step fail if there aren't any appropriate wheels? Pretty sure bash would give an error code there.

**Comment by auscompgeek** [comment]
bash wouldn't error, but mv would, since the wildcard wouldn't be expanded in that case.

**Pull request merged**
