### PR TITLE
manylinux_2_27 support

### PR DESCRIPTION
**Pull request by TheTripleV**
Changes from the previous pr: correct the manylinux tag to `manylinux_2_27_x86_64`

### CODE REVIEW

**Comment by TheTripleV** [comment]
I built a wheel locally on ubuntu 18.04, ran this script, and installed the renamed wheel successfully.

**Comment by virtuald** [comment]
I don't really want to merge this until after the first round of releases is out; I can go manually rename things on tortall

**Comment by TheTripleV** [comment]
This PR should be accompanied by CI pushing linux wheels to pypi anyway.

**Comment by auscompgeek** [comment]
Yup, doing this currently makes little sense whilst we're hosting the Linux wheels elsewhere.

**Pull request merged**
